global:
  scrape_interval: 15s       # How often to scrape targets by default
  evaluation_interval: 15s     # How often to evaluate rules

scrape_configs:
  - job_name: 'mlip_app'
    metrics_path: '/metrics'   # This should match the endpoint you expose in your Flask app
    static_configs:
      - targets: ['localhost:5000']   # Update with your app's hostname and port
